dist: focal
language: d
d:
 - dmd-2.093.0

addons:
  apt:
    packages:
    - xorg-dev # X11 dev
    - xvfb # virtual framebuffer

install:
  - git clone https://github.com/xdrie/raylib.git # get raylib
  - pushd raylib && git checkout 3.0.0_patch && git submodule update --init --recursive && popd # get the patched branch, and raygui
  - pushd raylib/src && make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE -j$(nproc) && sudo make install PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE && popd
script:
 - dub test -b unittest-cov --compiler=${DC}
after_success:
 - bash <(curl -s https://codecov.io/bash)