language: d
d:
 - dmd-2.093.0

install:
  - git clone --recursive https://github.com/xdrie/raylib.git # get raylib
  - pushd raylib && git checkout 3.0.0_patch && popd # get the patched branch
  - pushd raylib/src && make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE -j$(nproc) && sudo make install PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE && popd
script:
 - dub test -b unittest-cov --compiler=${DC}
after_success:
 - bash <(curl -s https://codecov.io/bash)