name: windows
on: [ push, pull_request ]
jobs:
  test-windows:
    runs-on: windows-latest
    env:
      RAYLIB_PREBUILD_VERSION: 5.0.0-r1
      DRAY_VERSION: 5.0.0-r4
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v2
      with:
        compiler: ldc
    - name: 'Setup Windows Build Environment'
      shell: pwsh
      run: |
        git submodule update --init --recursive
        
        echo "get raylib prebuild"
        curl -L https://github.com/redthing1/dray/releases/download/v$env:RAYLIB_PREBUILD_VERSION/raylib-dev_win64_msvc16.zip.zip --output raylib-dev_win64_msvc16.zip.zip
        7z x raylib-dev_win64_msvc16.zip.zip
        7z x raylib-dev_win64_msvc16.zip

        curl -L https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.WIN64.zip --output glfw-3.4.bin.WIN64.zip
        unzip glfw-3.4.bin.WIN64.zip
        move glfw-3.4.bin.WIN64/lib-vc2022/glfw3_mt.lib ./glfw3_mt.lib

        echo "prebuild dray with libs"
        dub fetch dray@$env:DRAY_VERSION
        $DRAY_PATH = "$env:LOCALAPPDATA/dub/packages/dray/$env:DRAY_VERSION/dray"
        echo "using dray path: $DRAY_PATH"
        dub list dray@$env:DRAY_VERSION
        cp raylib-dev_win64_msvc16/lib/raylib.lib $DRAY_PATH/raylib.lib
        cp glfw3_mt.lib $DRAY_PATH/glfw3_mt.lib
        dub build dray@$env:DRAY_VERSION
        ls $DRAY_PATH

        echo "show files"
        dir
    - name: 'Build'
      run: |
        dub build
    - name: 'Run Tests'
      run: |
        dub test
    - name: 'Build Demos'
      # run dub build in each demo/ folder, but ignore folders that don't have a dub.sdl
      # using powershell syntax
      shell: powershell
      run: |
        $demos = Get-ChildItem -Path ./demo -Directory -Recurse
        foreach ($demo in $demos) {
          if (Test-Path "$($demo.FullName)/dub.sdl") {
            pushd $demo.FullName
            dub build
            popd
          }
        }
    - name: 'Package'
      run: |
        dir
        7z a rengfx_win_builddir.7z .
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: rengfx-win-builddir
        path: rengfx_win_builddir.7z
