name: windows
on: [ push, pull_request ]
jobs:
  test-windows:
    runs-on: windows-latest
    env:
      DRAY_VERSION: v4.2.0-r2
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
    - name: 'Setup Windows Build Environment'
      run: |
        git submodule update --init --recursive
        curl -L https://github.com/ldc-developers/ldc/releases/download/v1.29.0/ldc2-1.29.0-windows-x64.7z --output ldc2-1.29.0-windows-x64.7z
        7z x ldc2-1.29.0-windows-x64.7z
        curl -L https://github.com/redthing1/dray/releases/download/v$DRAY_VERSION/raylib-dev_win64_msvc16.zip.zip --output raylib-dev_win64_msvc16.zip.zip
        7z x raylib-dev_win64_msvc16.zip.zip
        7z x raylib-dev_win64_msvc16.zip
        curl -L https://github.com/redthing1/dray/releases/download/v4.0.0-r3/winlibs_extra.7z --output winlibs_extra.7z
        7z x winlibs_extra.7z
        curl -L https://github.com/glfw/glfw/releases/download/3.3.7/glfw-3.3.7.bin.WIN64.zip --output glfw-3.3.7.bin.WIN64.zip
        unzip glfw-3.3.7.bin.WIN64.zip
        move glfw-3.3.7.bin.WIN64/lib-vc2022/glfw3_mt.lib ./glfw3_mt.lib
        cd ext
        git clone --depth 1 --branch v$DRAY_VERSION https://github.com/redthing1/dray
        cd dray
        move ../../raylib-dev_win64_msvc16/lib/raylib.lib ./raylib.lib
        move ../../WinMM.lib ./WinMM.lib
        set WINLIB_BASE="../../ldc2-1.28.1-windows-x64/lib/"
        set WINLIB_MINGW="../../ldc2-1.28.1-windows-x64/lib/mingw"
        echo $WINLIB_BASE
        dub build
        cd ../..
        move ext/dray/WinMM.lib ./WinMM.lib
    - name: 'Build'
      run: |
        dub add-override dray $DRAY_VERSION ./ext/dray
        move ext/dray/raylib.lib ./raylib.lib
        dub build
    
    - name: 'Run Tests'
      run: |
        dub test